### ISSUE TITLE
process killed

### ISSUE THREAD

**Issue by leonardodora** [harlanhong/ICCV2023-MCNET#2]
hi, when I run the command 
' CUDA_VISIBLE_DEVICES=0 python demo.py  --config config/vox-256.yaml --driving_video crop.mp4 --source_image test_images/a3.jpg --checkpoint 00000099-checkpoint.pth.tar --relative --adapt_scale --kp_num 15 --generator Unet_Generator_keypoint_aware --result_video result.mp4 --mbunit ExpendMemoryUnit --memsize 1 '
the process has been killed in the middle without any prompt. Could you please help me to find out the reason?

**Comment by harlanhong** [comment]
Could you send me your driving video and source image?

**Comment by leonardodora** [comment]
> 

sorry, I have find out the reason. The crop video is too long
