### ISSUE TITLE
Question about table 1

### ISSUE THREAD

**Issue by Pixie8888** [harlanhong/ICCV2023-MCNET#23]
Dear authors,

Does your model only trained on VoxCeleb dataset, but it is evaluated on VoxCeleb and CelebV? Because I am confused by the sentence ``` Following DaGAN, to verify the generalization ability, we apply the model trained on VoxCeleb1 to test on CelebV``` in your paper.

**Comment by harlanhong** [comment]
Yes. It only train on Voxcelebv
