### ISSUE TITLE
Questions about pairing the original image with the driving frame with same id

### ISSUE THREAD

**Issue by Li-ChengYan** [harlanhong/ICCV2023-MCNET#5]
Thank you for your excellent work. I'm trying to reproduce your work, but I have some problems. You said, "The source image and the driving video share the same identity in the training stage, so the sampled driving frame can be used as the ground-truth of a generated source-identity image." in your paper. But I noticed that in the code file "vox256.csv" seems like not aligh you paper's word, that the source image and the driving frame do not share the same id. So I'm litil bit confused about that, please tell me the correct trainning dataset configs.  Thank you!

**Comment by harlanhong** [comment]
Hi, The vox256.csv has nothing to do with the training stage. Please just ignore it. And during the training stage, we just randomly sample two frames from a video and take one as the source image and the other one as driving image.

**Comment by Li-ChengYan** [comment]
OK，Thank you very much!
