### ISSUE TITLE
Training Hyperparameters?

### ISSUE THREAD

**Issue by movingright** [harlanhong/ICCV2023-MCNET#8]
Could you confirm if the training hyperparameters in vox-256.yaml are configured correctly?

I'm particularly puzzled about the generator_gan loss weight being set to 0, as seen here: https://github.com/harlanhong/ICCV2023-MCNET/blob/master/config/vox-256.yaml#L74. If I understand correctly, doesn't this imply that the discriminator's weights remain unchanged throughout training? https://github.com/harlanhong/ICCV2023-MCNET/blob/master/train.py#L138

Can you please clarify?

**Comment by harlanhong** [comment]
Yes, we set the generator_gan to 0 so we don't train the model in a GAN manner but a VAE manner. In our experiments, using GAN to train this model doesn't gain any improvement but increases the burden of GPU.

**Comment by movingright** [comment]
I see, thanks helpful, thanks @harlanhong
